name: typo3-ter-release
run-name: Release on TYPO3 TER

on:
  workflow_call:
    inputs:
      php-version:
        default: '8.1'
        type: string
    secrets:
      api-token:
        required: true

jobs:
  ter-release:
    runs-on: ubuntu-latest
    steps:
      # Setup PHP and composer
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          extensions: intl, mbstring, json, zip, curl
          tools: composer:v2

      # Install tailor CLI
      - name: Install tailor
        run: composer global require typo3/tailor --prefer-dist --no-progress --no-suggest

      - name: Publish extension to TER
        run: TYPO3_API_TOKEN="${{ secrets.api-token }}" php ~/.composer/vendor/bin/tailor ter:publish --comment "${{ github.event.release.body }}" --artefact "${{ github.event.release.zipball_url }}" ${{ github.event.release.tag_name }}
